apiVersion: batch/v1
kind: Job
metadata:
  name: customer-etl-job
spec:
  template:
    spec:
      containers:
      - name: spark-etl
        image: your-dockerhub-username/spark-etl:latest
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: password
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_DB
          value: demo_db
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      restartPolicy: Never
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc