name: CI/CD for Spark ETL

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/spark-etl:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/spark-etl:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/postgres-deployment.yaml
        kubectl apply -f kubernetes/postgres-service.yaml
        kubectl apply -f kubernetes/spark-job.yaml